version: '3.4'

services:
  candatabasemanagementsystem.webapi:
    image: ${DOCKER_REGISTRY-}candatabasemanagementsystemwebapi
    build:
      context: .
      dockerfile: CanDatabaseManagementSystem.WebApi/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - mynetwork
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    hostname: db
    environment:
      ACCEPT_EULA: Y
      USER: sa
      SA_PASSWORD: CanDatabase111
    ports:
        - 1433:1433
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - mynetwork
  candatabasemanagementsystem.ui:
    image: ${DOCKER_REGISTRY-}candatabasemanagementsystemui
    build:
      context: .
      dockerfile: CanDatabaseManagementSystem.UI/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - mynetwork
    depends_on:
      - candatabasemanagementsystem.webapi

volumes:
  mssql_data:
networks:
  mynetwork:
    driver: bridge
